### ISSUE TITLE
UI dev

### ISSUE THREAD

**Issue by SutherChri** [tnx21/Comp-Mddn-Game#3]

**Comment by SutherChri** [comment]
[MenuUI.zip](https://github.com/tnx21/Comp-Mddn-Game/files/2398865/MenuUI.zip)

**Comment by SutherChri** [comment]
![dashicon](https://user-images.githubusercontent.com/36978503/45786811-59be7280-bcc6-11e8-9fdf-5bdb344682ac.png)
WIP ui for Dash ability

**Comment by SutherChri** [comment]
![abilitiyui](https://user-images.githubusercontent.com/36978503/45788741-765fa800-bcd0-11e8-8bfc-82d9fe9d8426.png)

Added new images.

**Comment by SoBrodacious** [comment]
Good work, fantastic
