### ISSUE TITLE
Playtesting Feedback - cherryryan - Ryan Cherry

### ISSUE THREAD

**Issue by Ryanasaurus** [tnx21/Comp-Mddn-Game#35]
Good game, but feels really janky. Movement feels slow. Wall jumping is really odd, and didn't feel like a feature. It felt more like a bug, as the player model walked into the wall. Abilities weren't very well advertised, I found wall jumping, ground pounding, and dashing, through mistakes of my own. How to progress through the level isnt very clear either, as it doesnt feel like theres anywhere to go, as well as getting stuck not knowing how to perform different actions.

**Comment by koyawase** [comment]
The movement is one of the main aspects we're looking to improve as it's the main mechanic of the game. We're looking to either increase the speed of the movement to match the animation or decrease the speed of the animation the match the player speed. At this point we're looking to decrease the speed of the animation as if we increase the player speed the game would be too fast.

We are looking to implement an animation for the wall jump so it fits well with the game.

The idea is to pick up power ups which will give a text dialogue of what abilities the player unlocked and how to use them to make it clear what the player abilities do and how to use them. We do not expect the player to know how to use all the controls without any guidance.
