### ISSUE TITLE
Playtesting feedback - idrismoha2 - Mohamed Ishaq Idris

### ISSUE THREAD

**Issue by IshaqIdris** [tnx21/Comp-Mddn-Game#36]
> Overall I loved the low poly aesthetic of the game. It was very pleasing to the eye.

- However I felt the mechanics of the player itself did not match the aesthetics and animations of the game.
  - I thought this was due to the player movement being too slow compared to the speed of the walking/running animation.
  - Also another issue with the game was I felt it was too "janky" especially when wall jumping as the player could stick to the wall for any amount of time instead of a fluid motion up.
- Also a way to die or damage itself would be interesting as their was currently no way to do this in the game. By doing this would add a challenge aspect to the game
- Also I felt the "w" key should be jump instead of "space" as I kept pressing the "w" key to jump while play testing the game.

> However again I really enjoyed the aesthetics of the game and see some good potential for further development

**Comment by koyawase** [comment]
1. The speed of the animation/gameplay has been discussed. If we increase the speed to match the animation, the game will be too fast to play. So we have decided to change the animation to match the current speed of the game. 
We are also trying to implement an animation for the player sticking on the wall. We aren't looking to change the actual mechanics of this as it would probably be too difficult to find an elegant solution with the time remaining. We are hoping that the added animation will be enough for the wall jump to look and work well.

2. The team was discussing ways for the player to die. We were thinking of either adding some sort of traps that the player has to avoid or making some difficult platforming that will require player skill to overcome. 

3. It would be good to utilise the "w" key in the game. We hadn't thought of that before. Having both "w" and spacebar for jump would give the user more flexibility to play the game on how they're comfortable with and would be an easy fix.
